function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 13-Sep-2018 12:27:11

% Create figure
figure1 = figure('Name','Figure');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Original','LineWidth',1);

% Create plot
plot(X2,Y2,'DisplayName','SPline','LineWidth',1,'Color',[1 0 0]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',12);

